#  eureka 服务治理的远程注册地址
eureka:
  global:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: 127.0.0.1
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

# 全局配置
global:
  config:
    ip: 127.0.0.1


# 消费者
service-consume:
  name: service-consume
  port: 8080
# 第一个服务的提供者
service-provide-1:
  name: service-provide-1
  port: 8081
# 第二个服务的提供者
service-provide-2:
  name: service-provide-2
  port: 8082
#eureka port  服务治理
spring-eureka:
  name: spring-eureka
  port: 8761
#zuul port 网关
spring-zuul:
  name: spring-zuul
  port: 8420
#zuul hystrix 断路器
spring-hystrix:
  name: spring-hystrix
  port: 8421
hystrix-dashboard:
  name: hystrix-dashboard
  port: 8422
spring-feign:
  name: spring-feign
  port: 8423
spring-config:
  name: spring-config
  port: 8424
spring-config-client:
  name: spring-config-client
    port: 8425