spring:
  profiles:
    active: global
  application:
    name: ${spring-eureka.name}
  zipkin:
    base-url: ${zikin.base.ip}:${spring-zuul.port}
server:
  port: ${spring-eureka.port}
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
