spring:
  application:
    name: ${spring-feign.name}
  profiles:
    active: global
  zipkin:
    base-url: ${zikin.base.ip}:${spring-zipkin.port}
eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
    ip-address: ${eureka.global.ip-address}
    instance-id: ${eureka.instance.ip-address}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${eureka.global.client.service-url.defaultZone}
server:
  port: ${spring-feign.port}
#   请求压缩
feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true
